@component('comps.error')
    @slot('error')
        @lang('errors.401')
    @endslot
    @slot('title')
        @lang('errors.401_title')
    @endslot
    @lang('errors.401_description')
@endcomponent