version: '3'

services:
  reciper_php:
    build: ./docker/php
    container_name: reciper_php
    volumes: 
      - ./:/var/www
      - ./docker/php/sites-available:/etc/apache2/sites-available
    ports: 
      - 3000:80
    working_dir: /var/www
    depends_on: 
      - reciper_db

  reciper_db:
    image: mysql:8.0
    container_name: reciper_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: reciper
    ports:
      - 1000:3306
    volumes: 
      - ./docker/db/storage:/var/lib/mysql

  reciper_composer:
    image: composer
    container_name: reciper_composer
    volumes: 
      - ./:/var/www
    working_dir: /var/www
    command: composer install --ignore-platform-reqs

  reciper_node:
    image: node:8-alpine
    container_name: reciper_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm rebuild node-sass && npm install && npm run production"

  reciper_redis:
    image: redis:5.0
    container_name: reciper_redis
    ports:
      - 6380:6379

  # reciper_selenium:
  #   image: selenium/standalone-chrome
  #   container_name: reciper_selenium
  #   ports:
  #     - "4444:4444"
