version: '3'

services:
  reciper_nginx:
    image: nginx:1.15
    container_name: reciper_nginx
    working_dir: /var/www
    depends_on: 
      - reciper_db
    ports:
      - 3000:80
    links:
      - reciper_php
    volumes:
      - ./services/php/src:/var/www
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/logs:/var/log/nginx

  reciper_php:
    image: serhiicho/reciper:php
    # build: services/php
    working_dir: /var/www
    container_name: reciper_php
    ports: 
      - 9002:9000
    volumes: 
      - ./services/php/src:/var/www
      - ./services/php/php-fpm.conf:/etc/php-fpm.d/php-fpm.conf
      - ./services/php/logs:/var/log/php

  reciper_db:
    image: mysql:8.0
    container_name: reciper_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: reciper
    ports:
      - 1000:3306
    volumes: 
      - ./services/db/storage:/var/lib/mysql

  reciper_composer_php:
    image: composer
    container_name: reciper_composer_php
    volumes: 
      - ./services/php/src:/var/www
    working_dir: /var/www
    command: composer install --ignore-platform-reqs

  reciper_composer_api:
    image: composer
    container_name: reciper_composer_api
    volumes: 
      - ./services/api/src:/var/www
    working_dir: /var/www
    command: composer install --ignore-platform-reqs

  reciper_node:
    image: node:8-alpine
    container_name: reciper_node
    working_dir: /var/www
    volumes:
      - ./services/php/src:/var/www
    command: sh -c "npm rebuild node-sass && npm install && npm run production"

  reciper_redis:
    image: redis:5.0
    container_name: reciper_redis
    ports:
      - 6380:6379

  reciper_api:
    # image: serhiicho/reciper:php
    build: services/api
    working_dir: /var/www
    container_name: reciper_api
    ports: 
      - 9003:9000
    volumes: 
      - ./services/api/src:/var/www
      - ./services/api/php-fpm.conf:/etc/php-fpm.d/php-fpm.conf
      - ./services/api/logs:/var/log/php

  # reciper_selenium:
  #   image: selenium/standalone-chrome
  #   container_name: reciper_selenium
  #   ports:
  #     - "4444:4444"
