version: '3'

services:
  server:
    build: ./docker/server
    container_name: server
    environment: 
      - APACHE_RUN_USER=#1000
    volumes: 
      - ./:/var/www
      - ./docker/server/sites-available:/etc/apache2/sites-available
    ports: 
      - 80:80
    working_dir: /var/www

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: reciper
    volumes: 
      - ./docker/db:/var/lib/mysql

  composer:
    image: composer
    container_name: composer
    volumes: 
      - ./:/var/www
    working_dir: /var/www
    command: composer install --ignore-platform-reqs

  node:
    image: node:8-alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm rebuild node-sass && npm install && npm run production"

  cache:
    image: redis:5.0
    container_name: redis
    ports:
      - 6379:6379

  # selenium-hub:
  #   image: selenium/hub:3.141.59-copernicium
  #   container_name: selenium-hub
  #   volumes:
  #     - /docker/selenium/dev/shm:/dev/shm
  #   ports:
  #     - "4444:4444"

  # chrome:
  #   image: selenium/node-chrome:3.141.59-copernicium
  #   container_name: chrome
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
