@component('comps.error')
    @slot('error')
        @lang('errors.403')
    @endslot
    @slot('title')
        @lang('errors.403_title')
    @endslot
    @lang('errors.403_description')
@endcomponent